language: php
php:
  - '7.0'
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit --configuration phpunit.xml.dist  --coverage-text

notifications:
    on_success: never
    on_failure: always
